#!/usr/bin/env bash
# ============================================================================
# CRITICAL-PATHS quality gate — SCAFFOLD STUB (auto-generated by
# tools/critical_paths_gate.py, scaffold command).
#
# WHEEL RULE (Mario, 2026-07-01): a spoke may not close/converge without
# proving its critical paths still work. /wai-closeout HARD-BLOCKS on red;
# /wai-converge uses this as its default test gate when present.
#
# THIS STUB IS INTENTIONALLY RED. It is NOT a fake pass — per the wheel rule,
# no gate may fake green. Replace this file with REAL, deterministic tests
# over THIS spoke's actual critical paths (the core user-facing flows this
# project exists to deliver). Reference pattern:
#   pathfinder: tests/critical_paths.sh (81 real deterministic tests, green) — the reference implementation for this gate.
#
# Until real tests replace this stub, the gate stays RED by design — that is
# the honest signal that critical-path coverage does not exist yet for this
# spoke. Do NOT change this to `exit 0` to unblock closeout/converge.
# ============================================================================
set -uo pipefail
echo "CRITICAL-PATHS GATE: NOT YET IMPLEMENTED for this spoke."
echo "This is a scaffolded stub (tools/critical_paths_gate.py) — it stays red"
echo "until real deterministic tests are written for this spoke's critical"
echo "paths. Reference: pathfinder: tests/critical_paths.sh (81 real deterministic tests, green) — the reference implementation for this gate."
exit 1
