#!/usr/bin/env python3
"""critical_paths_gate.py — WHEEL RULE (Mario, 2026-07-01): a spoke may not
close/converge without proving its critical paths via a REAL gate.

Reference implementation: pathfinder's tests/critical_paths.sh (81 real
deterministic tests, green — the pattern to copy). This module is the single
shared enforcement point used by:
  - /wai-closeout   Step 0a: HARD BLOCK on red (green required to ship).
  - /wai-converge   converge_closeout.py._detect_test_cmd: default test-cmd
                    when the gate is present.
  - the scaffolder: spokes missing the gate get a stub that FAILS until real
                    tests replace it (NO FAKES — a scaffolded stub must never
                    exit 0).
  - wai-health:     presence + last recorded result, via the ledger this
                    module writes on every `check` run.

CLI:
  check    --repo R [--base B] [--json]   run the gate if present, record the
                                           result to the ledger (if --base
                                           given); exit 0 = not blocking
                                           (green OR absent), exit 1 = RED.
  scaffold --repo R [--force] [--json]    write a failing stub at
                                           tests/critical_paths.sh if missing.
  status   --repo R [--base B] [--json]   read-only: presence + last ledger
                                           result (no gate execution — safe
                                           for wakeup/health-weight checks).
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

GATE_REL = os.path.join("tests", "critical_paths.sh")
LEDGER_REL = os.path.join("runtime", "critical-paths-gate.json")

REFERENCE_NOTE = (
    "pathfinder: tests/critical_paths.sh (81 real deterministic tests, green) "
    "— the reference implementation for this gate."
)

STUB_TEMPLATE = '''#!/usr/bin/env bash
# ============================================================================
# CRITICAL-PATHS quality gate — SCAFFOLD STUB (auto-generated by
# tools/critical_paths_gate.py, scaffold command).
#
# WHEEL RULE (Mario, 2026-07-01): a spoke may not close/converge without
# proving its critical paths still work. /wai-closeout HARD-BLOCKS on red;
# /wai-converge uses this as its default test gate when present.
#
# THIS STUB IS INTENTIONALLY RED. It is NOT a fake pass — per the wheel rule,
# no gate may fake green. Replace this file with REAL, deterministic tests
# over THIS spoke's actual critical paths (the core user-facing flows this
# project exists to deliver). Reference pattern:
#   {reference}
#
# Until real tests replace this stub, the gate stays RED by design — that is
# the honest signal that critical-path coverage does not exist yet for this
# spoke. Do NOT change this to `exit 0` to unblock closeout/converge.
# ============================================================================
set -uo pipefail
echo "CRITICAL-PATHS GATE: NOT YET IMPLEMENTED for this spoke."
echo "This is a scaffolded stub (tools/critical_paths_gate.py) — it stays red"
echo "until real deterministic tests are written for this spoke's critical"
echo "paths. Reference: {reference}"
exit 1
'''


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def gate_path(repo: str) -> str:
    return os.path.join(repo, GATE_REL)


def gate_present(repo: str) -> bool:
    return os.path.isfile(gate_path(repo))


def _ledger_path(base: str) -> str:
    return os.path.join(base, LEDGER_REL)


def record_result(base: str, result: dict, repo: str | None = None) -> str:
    """Persist the last gate outcome so wai-health / wakeup can report it
    without re-running the (potentially slow) gate themselves."""
    path = _ledger_path(base)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    payload = dict(result)
    payload["checked_at"] = _now_iso()
    if repo is not None:
        payload["repo"] = os.path.abspath(repo)
    Path(path).write_text(json.dumps(payload, indent=2) + "\n")
    return path


def read_ledger(base: str) -> dict | None:
    path = _ledger_path(base)
    if not os.path.exists(path):
        return None
    try:
        return json.loads(Path(path).read_text())
    except (OSError, json.JSONDecodeError):
        return None


def run_gate(repo: str) -> dict:
    """Run tests/critical_paths.sh if present. Absence is reported HONESTLY
    (status=absent) — it is not a pass, but it is also not what `check`
    blocks closeout on; only a present-and-RED gate blocks."""
    p = gate_path(repo)
    if not os.path.isfile(p):
        return {
            "present": False, "ran": False, "ok": True, "status": "absent",
            "detail": "tests/critical_paths.sh not found — spoke has not adopted "
                       "the wheel-rule gate yet (run scaffold to create a stub)",
        }
    r = subprocess.run(["bash", p], cwd=repo, capture_output=True, text=True)
    ok = r.returncode == 0
    tail_src = (r.stdout or "") + ("\n" + r.stderr if r.stderr else "")
    tail = [ln for ln in tail_src.strip().splitlines() if ln.strip()][-1:] or [""]
    return {
        "present": True, "ran": True, "ok": ok, "status": "green" if ok else "RED",
        "returncode": r.returncode, "detail": tail[0][:200],
    }


def scaffold_stub(repo: str, force: bool = False) -> dict:
    p = gate_path(repo)
    if os.path.exists(p) and not force:
        return {"scaffolded": False, "reason": "already exists", "path": p}
    os.makedirs(os.path.dirname(p), exist_ok=True)
    Path(p).write_text(STUB_TEMPLATE.format(reference=REFERENCE_NOTE))
    os.chmod(p, 0o755)
    return {"scaffolded": True, "path": p, "note": "stub is intentionally RED — replace with real tests"}


def status(repo: str, base: str | None = None) -> dict:
    """Read-only presence + last-known-result — no gate execution. Used by
    wai-health and wakeup so the check stays cheap."""
    out = {"present": gate_present(repo), "last_result": None}
    if base:
        out["last_result"] = read_ledger(base)
    return out


def check(repo: str, base: str | None = None) -> dict:
    """Run the gate (if present) and record the outcome. Returns the result
    dict; caller maps it to an exit code (RED-and-present => 1, else 0)."""
    result = run_gate(repo)
    if base:
        record_result(base, result, repo=repo)
    return result


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Wheel-rule critical-paths gate (WHEEL RULE 2026-07-01)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    c = sub.add_parser("check")
    c.add_argument("--repo", default=".")
    c.add_argument("--base", default=None)
    c.add_argument("--json", action="store_true")

    s = sub.add_parser("scaffold")
    s.add_argument("--repo", default=".")
    s.add_argument("--force", action="store_true")
    s.add_argument("--json", action="store_true")

    st = sub.add_parser("status")
    st.add_argument("--repo", default=".")
    st.add_argument("--base", default=None)
    st.add_argument("--json", action="store_true")

    args = ap.parse_args(argv)

    if args.cmd == "check":
        out = check(args.repo, args.base)
        blocked = out["present"] and not out["ok"]
        if args.json:
            print(json.dumps(out, indent=2))
        else:
            if not out["present"]:
                print("critical-paths gate: ABSENT (not adopted yet — not blocking)")
            elif out["ok"]:
                print(f"critical-paths gate: GREEN — {out.get('detail', '')}")
            else:
                print(f"critical-paths gate: RED — {out.get('detail', '')}")
                print("BLOCKED: green required to ship (WHEEL RULE 2026-07-01). Fix-forward, do not close/converge.")
        return 1 if blocked else 0

    if args.cmd == "scaffold":
        out = scaffold_stub(args.repo, force=args.force)
        if args.json:
            print(json.dumps(out, indent=2))
        else:
            print(json.dumps(out))
        return 0

    if args.cmd == "status":
        out = status(args.repo, args.base)
        if args.json:
            print(json.dumps(out, indent=2))
        else:
            print(json.dumps(out))
        return 0

    ap.error("unknown command")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
