#!/usr/bin/env python3
"""Disposition migration + health correction.

Brings a spoke's LOCAL lug data into the shape the operator/Ozi work split
expects, so that after an upgrade every spoke can answer "what needs the operator
vs what can Ozi run unattended" without any further human action.

CANON (operator-ratified 2026-07-19):

    the lug          disposition + disposition_reason + disposition_at   <- TRUTH
    ready-queue.json derived index regenerated by the expediter           <- CACHE

Truth lives on the lug because that is the only place that survives a restore
intact and needs no hub. The cache is disposable by construction.

WHAT THIS CORRECTS

  1. UNSTAMPED work lugs — a lug with no `disposition` is invisible to both
     buckets. Left alone it silently lands nowhere, which reads as a clear desk.
  2. STALE / MISSING ready-queue cache — regenerated via the expediter, its sole
     producer. Safe because `disposition_locked` pins operator-set values against
     re-derivation; only genuinely derived dispositions move, which is what
     refreshing a derived index means. --no-refresh-cache opts out.

WHAT IS PROTECTED

  A disposition the operator LOCKED (`disposition_locked: true`, or
  `disposition_source: operator`) is never rewritten by this migration or by the
  expediter. Everything unlocked stays derived. The migration itself only fills
  gaps and never re-derives what is already present; --restamp forces a full
  re-derivation as an explicit, separate act.

IDEMPOTENT. Detects its own prior work and no-ops. Safe to run on every upgrade,
including one that changed no files — which matters, because harness_upgrade only
reaches the migration hook when files actually moved, so a spoke already at the
target version would otherwise never self-heal.
"""

import argparse
import glob
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# The expediter owns disposition semantics. Importing rather than reimplementing
# keeps one definition of the operator/Ozi boundary — a second copy here would
# drift and produce two different answers to the same question.
try:
    from spoke_expediter import compute_disposition, score_lug_quality
    _EXPEDITER = True
except Exception:  # pragma: no cover - degraded mode, reported not hidden
    _EXPEDITER = False

# One definition of "stale", owned by work_split and shared here. Duplicating the
# threshold is how the two tools came to disagree about the same cache.
try:
    from work_split import _STALE_HOURS, _parse_ts
except Exception:  # pragma: no cover
    _STALE_HOURS = 24

    def _parse_ts(value):
        if not value or not isinstance(value, str):
            return None
        try:
            dt = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
        except ValueError:
            return None
        return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt

# Live-work states, imported from work_split so the two tools cannot disagree
# about what counts as backlog — the same single-owner rule applied to staleness
# after they diverged on it.
try:
    from work_split import LIVE_STATES as _STATES
except Exception:  # pragma: no cover
    _STATES = ("open", "in_progress", "active", "needs_attention", "undelivered",
               "draft", "deferred", "parked", "flagged", "acknowledged")


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


def _lugs_root(root):
    v4 = os.path.join(root, "WAI-Harness", "spoke", "local", "lugs")
    return v4 if os.path.isdir(v4) else os.path.join(root, "WAI-Spoke", "lugs")


def _advisors_root(root):
    v4 = os.path.join(root, "WAI-Harness", "spoke", "advisors")
    return v4 if os.path.isdir(v4) else os.path.join(root, "WAI-Spoke", "advisors")


def _iter_lug_paths(root):
    lugs = _lugs_root(root)
    for state in _STATES:
        for path in glob.glob(os.path.join(lugs, "bytype", "*", state, "*.json")):
            yield path


def _load(path):
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return None


def scan(root="."):
    """What is out of shape here? Read-only; the basis for both migrate and verify."""
    unstamped, total = [], 0
    for path in _iter_lug_paths(root):
        lug = _load(path)
        if not isinstance(lug, dict) or not lug.get("id"):
            continue
        total += 1
        if not lug.get("disposition"):
            unstamped.append(path)

    cache = os.path.join(_advisors_root(root), "expediter", "ready-queue.json")
    cache_blob = _load(cache)
    counts = (cache_blob or {}).get("counts") or {}
    # Staleness is defined ONCE, by work_split, and imported here.
    #
    # These two tools briefly disagreed: this scan called any present, non-zero
    # cache healthy while work_split called anything over _STALE_HOURS stale. A
    # brownfield dogfood then produced the worst possible pair of outputs -- verify
    # reporting CLEAN over a 21-day-old index that work_split was visibly
    # recomputing around. Two definitions of the same word is how a green light
    # stops meaning anything.
    cache_bad = cache_blob is None or (total > 0 and not counts.get("total"))
    if not cache_bad and cache_blob:
        generated = _parse_ts(cache_blob.get("generated_at"))
        if generated is None:
            cache_bad = True
        else:
            age_hours = (datetime.now(timezone.utc) - generated).total_seconds() / 3600.0
            cache_bad = age_hours > _STALE_HOURS

    return {
        "total_lugs": total,
        "unstamped": unstamped,
        "cache_path": cache,
        "cache_missing_or_zero": cache_bad,
    }


def migrate(root=".", dry_run=False, restamp=False, refresh_cache=True):
    """Stamp missing dispositions and refresh the derived cache.

    Counters increment in dry-run exactly as in a live run; only writes are gated,
    so --dry-run is a faithful preview rather than a different code path.
    """
    report = {
        "ts": _now_iso(),
        "root": os.path.abspath(root),
        "stamped": 0,
        "skipped_existing": 0,
        "cache_refreshed": False,
        "errors": [],
        "details": [],
        "dry_run": bool(dry_run),
    }

    if not _EXPEDITER:
        report["errors"].append(
            "spoke_expediter unavailable — cannot derive dispositions; "
            "migration reports FAILED rather than silently stamping nothing"
        )
        report["ok"] = False
        return report

    for path in _iter_lug_paths(root):
        lug = _load(path)
        if not isinstance(lug, dict) or not lug.get("id"):
            continue
        if lug.get("disposition") and not restamp:
            report["skipped_existing"] += 1
            continue
        try:
            # score_lug_quality returns (score, missing_fields) — compute_disposition
            # wants the scalar. Passing the tuple through silently compares tuple>=int
            # and raises, which is how the first dry-run failed on 10 of 12 lugs.
            quality, _missing = score_lug_quality(lug)
            disposition, reason = compute_disposition(lug, quality, root)
        except Exception as exc:  # one bad lug must never abort the sweep
            report["errors"].append("%s: %s" % (os.path.basename(path), exc))
            continue

        report["stamped"] += 1
        report["details"].append(
            {"id": lug["id"], "disposition": disposition, "reason": reason}
        )
        if dry_run:
            continue

        lug["disposition"] = disposition
        lug["disposition_reason"] = reason
        lug["disposition_at"] = _now_iso()
        # Provenance, matching savepoint_migrate: a later reader must be able to
        # tell a migration-derived stamp from one the expediter made in situ.
        lug["_migrated_by"] = "disposition_migrate"
        lug["_migrated_at"] = report["ts"]
        try:
            with open(path, "w", encoding="utf-8") as fh:
                json.dump(lug, fh, indent=2)
                fh.write("\n")
        except OSError as exc:
            report["errors"].append("write %s: %s" % (path, exc))

    # CACHE REFRESH — now safe by default, and it was not always.
    #
    # Refreshing the derived index runs the expediter, which re-derives disposition
    # on every lug it scores. That used to silently overwrite operator judgement
    # (measured: an operator-set `needs_you` came back `auto_build`), so this was
    # opt-in and the cache simply stayed stale — which dogfooding on a brownfield
    # spoke exposed as its own failure: the migration reported clean while leaving
    # an index nothing would ever repair.
    #
    # `disposition_locked` now pins operator-set values against re-derivation, so a
    # refresh touches only genuinely derived dispositions — which is what refreshing
    # a derived index is supposed to do. Default ON; --no-refresh-cache opts out.
    state = scan(root)
    if not refresh_cache:
        report["cache_refreshed"] = "skipped (--no-refresh-cache)"
        report["cache_needs_refresh"] = state["cache_missing_or_zero"]
    elif state["cache_missing_or_zero"] and not dry_run:
        report["cache_refreshed"] = _refresh_cache(root, report)
    elif state["cache_missing_or_zero"]:
        report["cache_refreshed"] = "would refresh"

    report["ok"] = not report["errors"]
    return report


def _refresh_cache(root, report):
    """Regenerate ready-queue.json by invoking the expediter, its sole producer.

    Shelling out rather than reimplementing: the expediter is the one writer of
    this artifact, and a second producer here would be exactly the drift the
    cache-not-truth rule exists to prevent.
    """
    tool = os.path.join(os.path.dirname(os.path.abspath(__file__)), "spoke_expediter.py")
    if not os.path.isfile(tool):
        report["errors"].append("spoke_expediter.py not found; cache not refreshed")
        return False
    import subprocess
    try:
        result = subprocess.run(
            [sys.executable, tool, "--spoke-path", root, "--all"],
            capture_output=True, text=True, timeout=300,
        )
        if result.returncode != 0:
            report["errors"].append("expediter exit %s: %s" % (result.returncode, result.stderr[:200]))
            return False
        return True
    except Exception as exc:
        report["errors"].append("expediter invocation failed: %s" % exc)
        return False


def verify_no_legacy(root="."):
    """Post-check consumed by harness_upgrade's --verify pass."""
    state = scan(root)
    # Cache freshness IS part of clean now that refresh is automatic and safe: a
    # migration that leaves an index nothing will ever repair is not clean, it is
    # quietly broken -- which is exactly what the brownfield dogfood surfaced.
    clean = not state["unstamped"] and not state["cache_missing_or_zero"]
    return {
        "clean": clean,
        "total_lugs": state["total_lugs"],
        "unstamped_remaining": len(state["unstamped"]),
        "cache_missing_or_zero": state["cache_missing_or_zero"],
        "ts": _now_iso(),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--verify", action="store_true")
    parser.add_argument(
        "--no-refresh-cache",
        action="store_true",
        help="skip regenerating ready-queue.json. Refresh is ON by default and is safe: "
             "disposition_locked pins operator-set values against the expediter's "
             "re-derivation, so only genuinely derived dispositions move.",
    )
    parser.add_argument(
        "--restamp",
        action="store_true",
        help="re-derive EVERY disposition, overwriting existing ones (explicit act, never automatic)",
    )
    args = parser.parse_args()

    if args.verify:
        result = verify_no_legacy(args.root)
        print(json.dumps(result, indent=2) if args.json else
              ("CLEAN" if result["clean"] else
               "GAPS: %d unstamped, cache_bad=%s" % (result["unstamped_remaining"], result["cache_missing_or_zero"])))
        return 0 if result["clean"] else 1

    report = migrate(args.root, dry_run=args.dry_run, restamp=args.restamp,
                     refresh_cache=not args.no_refresh_cache)
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print("stamped=%d skipped=%d cache_refreshed=%s errors=%d%s" % (
            report["stamped"], report["skipped_existing"],
            report["cache_refreshed"], len(report["errors"]),
            " (dry-run)" if report["dry_run"] else "",
        ))
        for err in report["errors"][:5]:
            print("  ERROR: %s" % err)
    return 0 if report.get("ok") else 1


if __name__ == "__main__":
    sys.exit(main())
