#!/usr/bin/env python3
"""Work split — what needs the operator vs what Ozi can take unattended.

Renders the wakeup's two-bucket view and answers the operator's standing question:
"what is actually stuck on me, and what can run without me?"

TRUTH MODEL (operator-ratified):

    the lug          disposition + disposition_reason + disposition_at   <- TRUTH
    ready-queue.json derived index, regenerated by the expediter          <- CACHE
    this renderer    reads the cache, falls back to the lugs              <- VIEW

The cache is NEVER authoritative. If ready-queue.json is missing, stale, or
internally zero while lugs exist on disk, this tool recomputes from the lugs and
says so. A stale cache must be a non-event; the failure this guards against is a
briefing confidently reporting "0 items need you" over a 500-lug backlog.

RANKING. The NEEDS YOU bucket is not sorted by age or ROI but by UNBLOCK LEVERAGE:
how many otherwise-autonomous lugs each operator-side item is gating, computed from
blocked_by edges. The point of the panel is to shrink the operator's blocking set,
so the top of the list is whatever frees the most work per decision.
"""

import argparse
import collections
import glob
import json
import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    import wai_paths
except ImportError:  # pragma: no cover
    wai_paths = None

# Types that never dispatch to an autonomous runner, mirroring conductor.py's
# _SKIP_TYPES and ozi_autopilot's _DISPATCHABLE_SKIP_TYPES. Kept in lockstep by
# test_wakeup_contract; if those diverge the split silently misreports.
SKIP_TYPES = frozenset({
    "epic", "signal", "spec", "idea", "review", "notation",
    "question", "notice", "session-summary", "feature",
})

# Dispositions that mean the operator is the blocker.
OPERATOR_SIDE = frozenset({"needs_you", "blocked"})

# A repair queue, NOT a third bucket of operator judgment. Every `review` lug
# carries a mechanical gap (missing file_targets, partial PEV, missing AC) that a
# grooming pass can fill. Counting these as operator work overstates the desk by
# ~84 items on the canonical spoke.
REPAIRABLE = "review"

# Lug STATE directories that hold live work.
#
# Measured on the canonical spoke 2026-07-20: 16 state dirs exist on disk while
# harness_upgrade._LUG_STATUSES names only three. Assuming open+in_progress left
# 64 lugs of live work invisible to the split -- active, needs_attention,
# undelivered, draft, deferred, parked, flagged, acknowledged -- which is a
# briefing under-reporting the backlog rather than a cosmetic gap.
#
# Terminal states are excluded deliberately: completed, closed, done, resolved,
# retired, delivered.
LIVE_STATES = (
    "open", "in_progress", "active", "needs_attention", "undelivered",
    "draft", "deferred", "parked", "flagged", "acknowledged",
)
TERMINAL_STATES = ("completed", "closed", "done", "resolved", "retired", "delivered")

_STALE_HOURS = 24


def _now():
    return datetime.now(timezone.utc)


def _parse_ts(value):
    if not value or not isinstance(value, str):
        return None
    try:
        dt = datetime.fromisoformat(value.strip().replace("Z", "+00:00"))
    except ValueError:
        return None
    return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt


def _advisors_root(spoke_root):
    if wai_paths is not None:
        resolved = wai_paths.advisors_dir(spoke_root)
        if resolved:
            return resolved
    v4 = os.path.join(spoke_root, "WAI-Harness", "spoke", "advisors")
    return v4 if os.path.isdir(v4) else os.path.join(spoke_root, "WAI-Spoke", "advisors")


def _lugs_root(spoke_root):
    v4 = os.path.join(spoke_root, "WAI-Harness", "spoke", "local", "lugs")
    return v4 if os.path.isdir(v4) else os.path.join(spoke_root, "WAI-Spoke", "lugs")


def load_lugs(spoke_root):
    """Every open / in-progress lug. This is the source of truth."""
    root = _lugs_root(spoke_root)
    out = []
    for state in LIVE_STATES:
        for path in glob.glob(os.path.join(root, "bytype", "*", state, "*.json")):
            try:
                with open(path, "r", encoding="utf-8") as fh:
                    lug = json.load(fh)
            except (OSError, ValueError):
                continue
            if isinstance(lug, dict) and lug.get("id"):
                lug["_path"] = path
                out.append(lug)
    return out


def is_dispatchable(lug):
    """Can an autonomous runner actually pick this up?

    Mirrors the real dispatch gate rather than trusting disposition alone: a lug
    can be stamped auto_build and still be undispatchable for want of target
    files, which is the difference between a promise and a run.
    """
    if lug.get("type") in SKIP_TYPES:
        return False
    if str(lug.get("risk_tier", "")).lower() == "critical":
        return False
    if str(lug.get("execution_mode", "")).lower() == "manual":
        return False
    execute_when = lug.get("execute_when")
    if isinstance(execute_when, dict) and execute_when.get("manual_gate"):
        return False
    return bool(lug.get("target_files") or lug.get("file_targets"))


def unblock_leverage(lugs):
    """operator-side lug id -> how many other lugs it gates.

    Only edges pointing at an unresolved operator-side lug count; a blocked_by
    naming something already completed is not a blocker, and treating it as one
    manufactures phantom work on the operator's desk.
    """
    by_id = {lug["id"]: lug for lug in lugs}
    gates = collections.Counter()
    for lug in lugs:
        for ref in lug.get("blocked_by") or []:
            blocker_id = ref if isinstance(ref, str) else (ref or {}).get("id", "")
            blocker = by_id.get(blocker_id)
            if blocker is None:
                continue
            if blocker.get("disposition") in OPERATOR_SIDE or blocker.get("disposition") == REPAIRABLE:
                gates[blocker_id] += 1
    return gates


def collect(spoke_root="."):
    lugs = load_lugs(spoke_root)
    cache_path = os.path.join(_advisors_root(spoke_root), "expediter", "ready-queue.json")

    cache = None
    cache_state = "absent"
    try:
        with open(cache_path, "r", encoding="utf-8") as fh:
            cache = json.load(fh)
    except (OSError, ValueError):
        cache = None

    if cache is not None:
        generated = _parse_ts(cache.get("generated_at"))
        age = (_now() - generated).total_seconds() / 3600.0 if generated else None
        counts = cache.get("counts") or {}
        # A zero-total cache over a non-empty backlog is the stale-zero failure:
        # it reports a clear desk that does not exist. Distrust it explicitly.
        if lugs and not counts.get("total"):
            cache_state = "stale-zero"
        elif age is not None and age > _STALE_HOURS:
            cache_state = "stale"
        else:
            cache_state = "fresh"

    # The lugs always decide. The cache is used for corroboration and reporting,
    # never as the sole source of the numbers below.
    gates = unblock_leverage(lugs)

    needs_you, autonomous, repairable = [], [], []
    for lug in lugs:
        disposition = lug.get("disposition")
        row = {
            "id": lug["id"],
            "type": lug.get("type", "?"),
            "title": (lug.get("title") or "")[:70],
            "disposition": disposition or "<unstamped>",
            "reason": (lug.get("disposition_reason") or "")[:80],
            "gates": gates.get(lug["id"], 0),
            "dispatchable": is_dispatchable(lug),
        }
        if disposition == REPAIRABLE:
            repairable.append(row)
        elif disposition in OPERATOR_SIDE:
            needs_you.append(row)
        elif disposition == "auto_build":
            autonomous.append(row)
        elif lug.get("type") in SKIP_TYPES:
            continue  # non-dispatch types are neither bucket
        else:
            # Unstamped work types fail SAFE onto the operator's side. Never let an
            # ungroomed lug drift into the autonomous pool by default.
            needs_you.append(row)

    needs_you.sort(key=lambda r: (-r["gates"], r["id"]))
    autonomous.sort(key=lambda r: (not r["dispatchable"], r["id"]))

    return {
        "generated_at": _now().isoformat(),
        "cache_path": cache_path,
        "cache_state": cache_state,
        "cache_counts": (cache or {}).get("counts", {}),
        "total_lugs": len(lugs),
        "needs_you": needs_you,
        "autonomous": autonomous,
        "repairable": repairable,
        "runnable_now": sum(1 for r in autonomous if r["dispatchable"]),
        "gated_lug_count": sum(gates.values()),
    }


def render(model, limit=5):
    if not model["total_lugs"]:
        return ""

    runnable = model["runnable_now"]
    needs_you = model["needs_you"]
    repairable = model["repairable"]

    lines = ["WORK SPLIT — who is blocking what"]

    if model["cache_state"] in ("stale-zero", "stale", "absent"):
        # Say it plainly rather than quietly recomputing: a cache that lies is
        # worth knowing about even when the view below is correct anyway.
        lines.append(
            "  (ready-queue cache %s — figures recomputed from lugs, which are the truth)"
            % model["cache_state"]
        )

    lines.append(
        "  %d need you  |  %d Ozi can run now  |  %d repairable by grooming"
        % (len(needs_you), runnable, len(repairable))
    )

    if needs_you:
        lines.append("")
        lines.append("  NEEDS YOU — ranked by how much they unblock")
        for row in needs_you[:limit]:
            gates = ("unblocks %d" % row["gates"]) if row["gates"] else "unblocks nothing yet"
            lines.append("    - %-52s %s" % (row["id"][:52], gates))
        if len(needs_you) > limit:
            lines.append("    ... %d more (work_split.py --all)" % (len(needs_you) - limit))

    if repairable:
        lines.append("")
        lines.append(
            "  REPAIRABLE — %d lugs blocked on a fillable gap, not on your judgment"
            % len(repairable)
        )

    lines.append("")
    # Name the ENTRY POINT, not the runner. Printing the raw script path sent the
    # operator to a command that needs --spoke-path and does not exist on PATH,
    # while `autopilot` alone resolved to an unrelated Ubuntu package.
    lines.append(
        "  OZI IS FREE — %d dispatchable now; run: ./autopilot --live   (./autopilot alone = preview)"
        % runnable
    )
    return "\n".join(lines)


def write_handoff(spoke_root=".", model=None):
    """Persist the operator-blocked handoff into _session_state.blocked_on_human.

    Called by closeout so the NEXT wakeup inherits what this session learned about
    the operator's blocking set instead of rediscovering it cold. Lives here rather
    than as a script embedded in the ceremony markdown: ceremony prose is untested
    and counts against a token budget, tool code is neither.
    """
    model = model or collect(spoke_root)
    state_path = os.path.join(
        spoke_root, "WAI-Harness", "spoke", "local", "WAI-State.json")
    if not os.path.isfile(state_path):
        state_path = os.path.join(spoke_root, "WAI-Spoke", "WAI-State.json")
    try:
        with open(state_path, "r", encoding="utf-8") as fh:
            state = json.load(fh)
    except (OSError, ValueError) as exc:
        return {"ok": False, "error": "cannot read WAI-State: %s" % exc}

    state.setdefault("_session_state", {})["blocked_on_human"] = {
        "count": len(model["needs_you"]),
        "runnable_without_me": model["runnable_now"],
        "repairable_by_grooming": len(model["repairable"]),
        # Ranked by unblock leverage, capped at 5: a handoff nobody reads is not a
        # handoff, and the top of this list is the operator's actual critical path.
        "top": [
            {"id": r["id"], "unblocks": r["gates"], "why": r["reason"][:120]}
            for r in model["needs_you"][:5]
        ],
        "captured_at": model["generated_at"],
    }
    try:
        with open(state_path, "w", encoding="utf-8") as fh:
            json.dump(state, fh, indent=2)
            fh.write("\n")
    except OSError as exc:
        return {"ok": False, "error": "cannot write WAI-State: %s" % exc}
    return {"ok": True, "count": len(model["needs_you"]), "state_path": state_path}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--spoke-root", default=".")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--all", action="store_true", help="render every entry")
    parser.add_argument("--limit", type=int, default=5)
    parser.add_argument(
        "--write-handoff", action="store_true",
        help="persist the operator-blocked handoff to _session_state.blocked_on_human "
             "(closeout calls this so the next wakeup inherits it)",
    )
    args = parser.parse_args()

    model = collect(args.spoke_root)

    if args.write_handoff:
        result = write_handoff(args.spoke_root, model)
        print(json.dumps(result, indent=2) if args.json else
              ("handoff written: %d blocking you" % result["count"] if result["ok"]
               else "HANDOFF FAILED: %s" % result["error"]))
        return 0 if result["ok"] else 1
    if args.json:
        print(json.dumps(model, indent=2))
        return 0
    text = render(model, limit=0 if args.all else args.limit)
    if text:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
